# Generated by Django 4.0.5 on 2022-06-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('sana', models.DateField()),
                ('qoshiqchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.qoshiqchi')),
            ],
        ),
        migrations.CreateModel(
            name='Qoshiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('eshitish_soni', models.IntegerField(default=0)),
                ('fayl', models.URLField()),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.albom')),
            ],
        ),
    ]
